name: Update Cache

on:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟触发一次定时任务
  workflow_dispatch:      # 可选: 支持手动触发

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Cache Update Script
        run: node .github/scripts/update-cache.js
